# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'switch_tester_config.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1445, 938)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_testCmmds = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_testCmmds.sizePolicy().hasHeightForWidth())
        self.tab_testCmmds.setSizePolicy(sizePolicy)
        self.tab_testCmmds.setObjectName("tab_testCmmds")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_testCmmds)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.frm_network = QtWidgets.QFrame(self.tab_testCmmds)
        self.frm_network.setStyleSheet("background-color: rgb(0, 170, 156)")
        self.frm_network.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_network.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_network.setObjectName("frm_network")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frm_network)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.wgt_debB = QtWidgets.QWidget(self.frm_network)
        self.wgt_debB.setEnabled(True)
        self.wgt_debB.setAutoFillBackground(False)
        self.wgt_debB.setStyleSheet("background-color: rgb(0, 170, 127)")
        self.wgt_debB.setObjectName("wgt_debB")
        self.lbl_hostname_debB = QtWidgets.QLabel(self.wgt_debB)
        self.lbl_hostname_debB.setGeometry(QtCore.QRect(10, 5, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_hostname_debB.setFont(font)
        self.lbl_hostname_debB.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lbl_hostname_debB.setObjectName("lbl_hostname_debB")
        self.tBtn_editHost_debB = QtWidgets.QToolButton(self.wgt_debB)
        self.tBtn_editHost_debB.setGeometry(QtCore.QRect(290, 10, 31, 31))
        self.tBtn_editHost_debB.setObjectName("tBtn_editHost_debB")
        self.lbl_mac_debB = QtWidgets.QLabel(self.wgt_debB)
        self.lbl_mac_debB.setGeometry(QtCore.QRect(10, 50, 271, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_mac_debB.setFont(font)
        self.lbl_mac_debB.setObjectName("lbl_mac_debB")
        self.lbl_ip_debB = QtWidgets.QLabel(self.wgt_debB)
        self.lbl_ip_debB.setGeometry(QtCore.QRect(10, 70, 271, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_ip_debB.setFont(font)
        self.lbl_ip_debB.setObjectName("lbl_ip_debB")
        self.lbl_mlticast_debB = QtWidgets.QLabel(self.wgt_debB)
        self.lbl_mlticast_debB.setGeometry(QtCore.QRect(10, 110, 271, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_mlticast_debB.setFont(font)
        self.lbl_mlticast_debB.setObjectName("lbl_mlticast_debB")
        self.lbl_rx_debB = QtWidgets.QLabel(self.wgt_debB)
        self.lbl_rx_debB.setGeometry(QtCore.QRect(10, 130, 271, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_rx_debB.setFont(font)
        self.lbl_rx_debB.setObjectName("lbl_rx_debB")
        self.lbl_tx_debB = QtWidgets.QLabel(self.wgt_debB)
        self.lbl_tx_debB.setGeometry(QtCore.QRect(10, 150, 271, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_tx_debB.setFont(font)
        self.lbl_tx_debB.setObjectName("lbl_tx_debB")
        self.lbl_mode_debB = QtWidgets.QLabel(self.wgt_debB)
        self.lbl_mode_debB.setGeometry(QtCore.QRect(10, 90, 271, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_mode_debB.setFont(font)
        self.lbl_mode_debB.setObjectName("lbl_mode_debB")
        self.gridLayout_6.addWidget(self.wgt_debB, 1, 0, 1, 1)
        self.frm_mainbtns = QtWidgets.QFrame(self.frm_network)
        self.frm_mainbtns.setStyleSheet("background-color: rgb(85, 85, 127)\n""")
        self.frm_mainbtns.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frm_mainbtns.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frm_mainbtns.setObjectName("frm_mainbtns")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frm_mainbtns)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_testSettings = QtWidgets.QPushButton(self.frm_mainbtns)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.btn_testSettings.setFont(font)
        self.btn_testSettings.setObjectName("btn_testSettings")
        self.verticalLayout.addWidget(self.btn_testSettings)
        self.btn_runTest = QtWidgets.QPushButton(self.frm_mainbtns)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.btn_runTest.setFont(font)
        self.btn_runTest.setObjectName("btn_runTest")
        self.verticalLayout.addWidget(self.btn_runTest)
        self.btn_exit = QtWidgets.QPushButton(self.frm_mainbtns)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.btn_exit.setFont(font)
        self.btn_exit.setObjectName("btn_exit")
        self.verticalLayout.addWidget(self.btn_exit)
        self.gridLayout_6.addWidget(self.frm_mainbtns, 2, 1, 1, 2)
        self.wgt_debH = QtWidgets.QWidget(self.frm_network)
        self.wgt_debH.setEnabled(True)
        self.wgt_debH.setAutoFillBackground(False)
        self.wgt_debH.setStyleSheet("background-color: rgb(0, 170, 127)")
        self.wgt_debH.setObjectName("wgt_debH")
        self.lbl_hostname_debH = QtWidgets.QLabel(self.wgt_debH)
        self.lbl_hostname_debH.setGeometry(QtCore.QRect(10, 5, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_hostname_debH.setFont(font)
        self.lbl_hostname_debH.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lbl_hostname_debH.setObjectName("lbl_hostname_debH")
        self.tBtn_editHost_debH = QtWidgets.QToolButton(self.wgt_debH)
        self.tBtn_editHost_debH.setGeometry(QtCore.QRect(290, 10, 31, 31))
        self.tBtn_editHost_debH.setObjectName("tBtn_editHost_debH")
        self.lbl_mac_debH = QtWidgets.QLabel(self.wgt_debH)
        self.lbl_mac_debH.setGeometry(QtCore.QRect(10, 50, 271, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_mac_debH.setFont(font)
        self.lbl_mac_debH.setObjectName("lbl_mac_debH")
        self.lbl_ip_debH = QtWidgets.QLabel(self.wgt_debH)
        self.lbl_ip_debH.setGeometry(QtCore.QRect(10, 70, 271, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_ip_debH.setFont(font)
        self.lbl_ip_debH.setObjectName("lbl_ip_debH")
        self.lbl_mlticast_debH = QtWidgets.QLabel(self.wgt_debH)
        self.lbl_mlticast_debH.setGeometry(QtCore.QRect(10, 110, 271, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_mlticast_debH.setFont(font)
        self.lbl_mlticast_debH.setObjectName("lbl_mlticast_debH")
        self.lbl_rx_debH = QtWidgets.QLabel(self.wgt_debH)
        self.lbl_rx_debH.setGeometry(QtCore.QRect(10, 130, 271, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_rx_debH.setFont(font)
        self.lbl_rx_debH.setObjectName("lbl_rx_debH")
        self.lbl_tx_debH = QtWidgets.QLabel(self.wgt_debH)
        self.lbl_tx_debH.setGeometry(QtCore.QRect(10, 150, 271, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_tx_debH.setFont(font)
        self.lbl_tx_debH.setObjectName("lbl_tx_debH")
        self.lbl_mode_debH = QtWidgets.QLabel(self.wgt_debH)
        self.lbl_mode_debH.setGeometry(QtCore.QRect(10, 90, 271, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_mode_debH.setFont(font)
        self.lbl_mode_debH.setObjectName("lbl_mode_debH")
        self.gridLayout_6.addWidget(self.wgt_debH, 3, 5, 1, 1)
        self.wgt_debG = QtWidgets.QWidget(self.frm_network)
        self.wgt_debG.setEnabled(True)
        self.wgt_debG.setAutoFillBackground(False)
        self.wgt_debG.setStyleSheet("background-color: rgb(0, 170, 127)")
        self.wgt_debG.setObjectName("wgt_debG")
        self.lbl_hostname_debG = QtWidgets.QLabel(self.wgt_debG)
        self.lbl_hostname_debG.setGeometry(QtCore.QRect(10, 5, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_hostname_debG.setFont(font)
        self.lbl_hostname_debG.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lbl_hostname_debG.setObjectName("lbl_hostname_debG")
        self.tBtn_editHost_debG = QtWidgets.QToolButton(self.wgt_debG)
        self.tBtn_editHost_debG.setGeometry(QtCore.QRect(290, 10, 31, 31))
        self.tBtn_editHost_debG.setObjectName("tBtn_editHost_debG")
        self.lbl_mac_debG = QtWidgets.QLabel(self.wgt_debG)
        self.lbl_mac_debG.setGeometry(QtCore.QRect(10, 50, 271, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_mac_debG.setFont(font)
        self.lbl_mac_debG.setObjectName("lbl_mac_debG")
        self.lbl_ip_debG = QtWidgets.QLabel(self.wgt_debG)
        self.lbl_ip_debG.setGeometry(QtCore.QRect(10, 70, 271, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_ip_debG.setFont(font)
        self.lbl_ip_debG.setObjectName("lbl_ip_debG")
        self.lbl_mlticast_debG = QtWidgets.QLabel(self.wgt_debG)
        self.lbl_mlticast_debG.setGeometry(QtCore.QRect(10, 110, 271, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_mlticast_debG.setFont(font)
        self.lbl_mlticast_debG.setObjectName("lbl_mlticast_debG")
        self.lbl_rx_debG = QtWidgets.QLabel(self.wgt_debG)
        self.lbl_rx_debG.setGeometry(QtCore.QRect(10, 130, 271, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_rx_debG.setFont(font)
        self.lbl_rx_debG.setObjectName("lbl_rx_debG")
        self.lbl_tx_debG = QtWidgets.QLabel(self.wgt_debG)
        self.lbl_tx_debG.setGeometry(QtCore.QRect(10, 150, 271, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_tx_debG.setFont(font)
        self.lbl_tx_debG.setObjectName("lbl_tx_debG")
        self.lbl_mode_debG = QtWidgets.QLabel(self.wgt_debG)
        self.lbl_mode_debG.setGeometry(QtCore.QRect(10, 90, 271, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_mode_debG.setFont(font)
        self.lbl_mode_debG.setObjectName("lbl_mode_debG")
        self.gridLayout_6.addWidget(self.wgt_debG, 2, 5, 1, 1)
        self.wgt_debD = QtWidgets.QWidget(self.frm_network)
        self.wgt_debD.setEnabled(True)
        self.wgt_debD.setAutoFillBackground(False)
        self.wgt_debD.setStyleSheet("background-color: rgb(0, 170, 127)")
        self.wgt_debD.setObjectName("wgt_debD")
        self.lbl_hostname_debD = QtWidgets.QLabel(self.wgt_debD)
        self.lbl_hostname_debD.setGeometry(QtCore.QRect(10, 5, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_hostname_debD.setFont(font)
        self.lbl_hostname_debD.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lbl_hostname_debD.setObjectName("lbl_hostname_debD")
        self.tBtn_editHost_debD = QtWidgets.QToolButton(self.wgt_debD)
        self.tBtn_editHost_debD.setGeometry(QtCore.QRect(290, 10, 31, 31))
        self.tBtn_editHost_debD.setObjectName("tBtn_editHost_debD")
        self.lbl_mac_debD = QtWidgets.QLabel(self.wgt_debD)
        self.lbl_mac_debD.setGeometry(QtCore.QRect(10, 50, 271, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_mac_debD.setFont(font)
        self.lbl_mac_debD.setObjectName("lbl_mac_debD")
        self.lbl_ip_debD = QtWidgets.QLabel(self.wgt_debD)
        self.lbl_ip_debD.setGeometry(QtCore.QRect(10, 70, 271, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_ip_debD.setFont(font)
        self.lbl_ip_debD.setObjectName("lbl_ip_debD")
        self.lbl_mlticast_debD = QtWidgets.QLabel(self.wgt_debD)
        self.lbl_mlticast_debD.setGeometry(QtCore.QRect(10, 110, 271, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_mlticast_debD.setFont(font)
        self.lbl_mlticast_debD.setObjectName("lbl_mlticast_debD")
        self.lbl_rx_debD = QtWidgets.QLabel(self.wgt_debD)
        self.lbl_rx_debD.setGeometry(QtCore.QRect(10, 130, 271, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_rx_debD.setFont(font)
        self.lbl_rx_debD.setObjectName("lbl_rx_debD")
        self.lbl_tx_debD = QtWidgets.QLabel(self.wgt_debD)
        self.lbl_tx_debD.setGeometry(QtCore.QRect(10, 150, 271, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_tx_debD.setFont(font)
        self.lbl_tx_debD.setObjectName("lbl_tx_debD")
        self.lbl_mode_debD = QtWidgets.QLabel(self.wgt_debD)
        self.lbl_mode_debD.setGeometry(QtCore.QRect(10, 90, 271, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_mode_debD.setFont(font)
        self.lbl_mode_debD.setObjectName("lbl_mode_debD")
        self.gridLayout_6.addWidget(self.wgt_debD, 3, 0, 1, 1)
        self.wgt_debE = QtWidgets.QWidget(self.frm_network)
        self.wgt_debE.setEnabled(True)
        self.wgt_debE.setAutoFillBackground(False)
        self.wgt_debE.setStyleSheet("background-color: rgb(0, 170, 127)")
        self.wgt_debE.setObjectName("wgt_debE")
        self.lbl_hostname_debE = QtWidgets.QLabel(self.wgt_debE)
        self.lbl_hostname_debE.setGeometry(QtCore.QRect(10, 5, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_hostname_debE.setFont(font)
        self.lbl_hostname_debE.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lbl_hostname_debE.setObjectName("lbl_hostname_debE")
        self.tBtn_editHost_debE = QtWidgets.QToolButton(self.wgt_debE)
        self.tBtn_editHost_debE.setGeometry(QtCore.QRect(290, 10, 31, 31))
        self.tBtn_editHost_debE.setObjectName("tBtn_editHost_debE")
        self.lbl_mac_debE = QtWidgets.QLabel(self.wgt_debE)
        self.lbl_mac_debE.setGeometry(QtCore.QRect(10, 50, 271, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_mac_debE.setFont(font)
        self.lbl_mac_debE.setObjectName("lbl_mac_debE")
        self.lbl_ip_debE = QtWidgets.QLabel(self.wgt_debE)
        self.lbl_ip_debE.setGeometry(QtCore.QRect(10, 70, 271, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_ip_debE.setFont(font)
        self.lbl_ip_debE.setObjectName("lbl_ip_debE")
        self.lbl_mlticast_debE = QtWidgets.QLabel(self.wgt_debE)
        self.lbl_mlticast_debE.setGeometry(QtCore.QRect(10, 110, 271, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_mlticast_debE.setFont(font)
        self.lbl_mlticast_debE.setObjectName("lbl_mlticast_debE")
        self.lbl_rx_debE = QtWidgets.QLabel(self.wgt_debE)
        self.lbl_rx_debE.setGeometry(QtCore.QRect(10, 130, 271, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_rx_debE.setFont(font)
        self.lbl_rx_debE.setObjectName("lbl_rx_debE")
        self.lbl_tx_debE = QtWidgets.QLabel(self.wgt_debE)
        self.lbl_tx_debE.setGeometry(QtCore.QRect(10, 150, 271, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_tx_debE.setFont(font)
        self.lbl_tx_debE.setObjectName("lbl_tx_debE")
        self.lbl_mode_debE = QtWidgets.QLabel(self.wgt_debE)
        self.lbl_mode_debE.setGeometry(QtCore.QRect(10, 90, 271, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_mode_debE.setFont(font)
        self.lbl_mode_debE.setObjectName("lbl_mode_debE")
        self.gridLayout_6.addWidget(self.wgt_debE, 0, 5, 1, 1)
        self.wgt_debF = QtWidgets.QWidget(self.frm_network)
        self.wgt_debF.setEnabled(True)
        self.wgt_debF.setAutoFillBackground(False)
        self.wgt_debF.setStyleSheet("background-color: rgb(0, 170, 127)")
        self.wgt_debF.setObjectName("wgt_debF")
        self.lbl_hostname_debF = QtWidgets.QLabel(self.wgt_debF)
        self.lbl_hostname_debF.setGeometry(QtCore.QRect(10, 5, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_hostname_debF.setFont(font)
        self.lbl_hostname_debF.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lbl_hostname_debF.setObjectName("lbl_hostname_debF")
        self.tBtn_editHost_debF = QtWidgets.QToolButton(self.wgt_debF)
        self.tBtn_editHost_debF.setGeometry(QtCore.QRect(290, 10, 31, 31))
        self.tBtn_editHost_debF.setObjectName("tBtn_editHost_debF")
        self.lbl_mac_debF = QtWidgets.QLabel(self.wgt_debF)
        self.lbl_mac_debF.setGeometry(QtCore.QRect(10, 50, 271, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_mac_debF.setFont(font)
        self.lbl_mac_debF.setObjectName("lbl_mac_debF")
        self.lbl_ip_debF = QtWidgets.QLabel(self.wgt_debF)
        self.lbl_ip_debF.setGeometry(QtCore.QRect(10, 70, 271, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_ip_debF.setFont(font)
        self.lbl_ip_debF.setObjectName("lbl_ip_debF")
        self.lbl_mlticast_debF = QtWidgets.QLabel(self.wgt_debF)
        self.lbl_mlticast_debF.setGeometry(QtCore.QRect(10, 110, 271, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_mlticast_debF.setFont(font)
        self.lbl_mlticast_debF.setObjectName("lbl_mlticast_debF")
        self.lbl_rx_debF = QtWidgets.QLabel(self.wgt_debF)
        self.lbl_rx_debF.setGeometry(QtCore.QRect(10, 130, 271, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_rx_debF.setFont(font)
        self.lbl_rx_debF.setObjectName("lbl_rx_debF")
        self.lbl_tx_debF = QtWidgets.QLabel(self.wgt_debF)
        self.lbl_tx_debF.setGeometry(QtCore.QRect(10, 150, 271, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_tx_debF.setFont(font)
        self.lbl_tx_debF.setObjectName("lbl_tx_debF")
        self.lbl_mode_debF = QtWidgets.QLabel(self.wgt_debF)
        self.lbl_mode_debF.setGeometry(QtCore.QRect(10, 90, 271, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_mode_debF.setFont(font)
        self.lbl_mode_debF.setObjectName("lbl_mode_debF")
        self.gridLayout_6.addWidget(self.wgt_debF, 1, 5, 1, 1)
        self.wgt_debA = QtWidgets.QWidget(self.frm_network)
        self.wgt_debA.setEnabled(True)
        self.wgt_debA.setAutoFillBackground(False)
        self.wgt_debA.setStyleSheet("background-color: rgb(0, 170, 127)")
        self.wgt_debA.setObjectName("wgt_debA")
        self.lbl_hostname_debA = QtWidgets.QLabel(self.wgt_debA)
        self.lbl_hostname_debA.setGeometry(QtCore.QRect(10, 5, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_hostname_debA.setFont(font)
        self.lbl_hostname_debA.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lbl_hostname_debA.setObjectName("lbl_hostname_debA")
        self.tBtn_editHost_debA = QtWidgets.QToolButton(self.wgt_debA)
        self.tBtn_editHost_debA.setGeometry(QtCore.QRect(290, 10, 31, 31))
        self.tBtn_editHost_debA.setObjectName("tBtn_editHost_debA")
        self.lbl_mac_debA = QtWidgets.QLabel(self.wgt_debA)
        self.lbl_mac_debA.setGeometry(QtCore.QRect(10, 50, 271, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_mac_debA.setFont(font)
        self.lbl_mac_debA.setObjectName("lbl_mac_debA")
        self.lbl_ip_debA = QtWidgets.QLabel(self.wgt_debA)
        self.lbl_ip_debA.setGeometry(QtCore.QRect(10, 70, 271, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_ip_debA.setFont(font)
        self.lbl_ip_debA.setObjectName("lbl_ip_debA")
        self.lbl_mlticast_debA = QtWidgets.QLabel(self.wgt_debA)
        self.lbl_mlticast_debA.setGeometry(QtCore.QRect(10, 110, 271, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_mlticast_debA.setFont(font)
        self.lbl_mlticast_debA.setObjectName("lbl_mlticast_debA")
        self.lbl_rx_debA = QtWidgets.QLabel(self.wgt_debA)
        self.lbl_rx_debA.setGeometry(QtCore.QRect(10, 130, 271, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_rx_debA.setFont(font)
        self.lbl_rx_debA.setObjectName("lbl_rx_debA")
        self.lbl_tx_debA = QtWidgets.QLabel(self.wgt_debA)
        self.lbl_tx_debA.setGeometry(QtCore.QRect(10, 150, 271, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_tx_debA.setFont(font)
        self.lbl_tx_debA.setObjectName("lbl_tx_debA")
        self.lbl_mode_debA = QtWidgets.QLabel(self.wgt_debA)
        self.lbl_mode_debA.setGeometry(QtCore.QRect(10, 90, 271, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_mode_debA.setFont(font)
        self.lbl_mode_debA.setObjectName("lbl_mode_debA")
        self.gridLayout_6.addWidget(self.wgt_debA, 0, 0, 1, 1)
        self.wgt_sw0 = QtWidgets.QWidget(self.frm_network)
        self.wgt_sw0.setEnabled(True)
        self.wgt_sw0.setAutoFillBackground(False)
        self.wgt_sw0.setStyleSheet("background-color: rgb(170, 85, 127)")
        self.wgt_sw0.setObjectName("wgt_sw0")
        self.lbl_switchname_sw0 = QtWidgets.QLabel(self.wgt_sw0)
        self.lbl_switchname_sw0.setGeometry(QtCore.QRect(10, 5, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_switchname_sw0.setFont(font)
        self.lbl_switchname_sw0.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lbl_switchname_sw0.setObjectName("lbl_switchname_sw0")
        self.lbl_rx_sw0 = QtWidgets.QLabel(self.wgt_sw0)
        self.lbl_rx_sw0.setGeometry(QtCore.QRect(10, 70, 311, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_rx_sw0.setFont(font)
        self.lbl_rx_sw0.setObjectName("lbl_rx_sw0")
        self.lbl_tx_sw0 = QtWidgets.QLabel(self.wgt_sw0)
        self.lbl_tx_sw0.setGeometry(QtCore.QRect(10, 90, 311, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_tx_sw0.setFont(font)
        self.lbl_tx_sw0.setObjectName("lbl_tx_sw0")
        self.tBtn_editSwitch_sw0 = QtWidgets.QToolButton(self.wgt_sw0)
        self.tBtn_editSwitch_sw0.setGeometry(QtCore.QRect(290, 10, 31, 31))
        self.tBtn_editSwitch_sw0.setObjectName("tBtn_editSwitch_sw0")
        self.lbl_sship_sw0 = QtWidgets.QLabel(self.wgt_sw0)
        self.lbl_sship_sw0.setGeometry(QtCore.QRect(10, 50, 311, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_sship_sw0.setFont(font)
        self.lbl_sship_sw0.setObjectName("lbl_sship_sw0")
        self.gridLayout_6.addWidget(self.wgt_sw0, 1, 1, 1, 1)
        self.wgt_debC = QtWidgets.QWidget(self.frm_network)
        self.wgt_debC.setEnabled(True)
        self.wgt_debC.setAutoFillBackground(False)
        self.wgt_debC.setStyleSheet("background-color: rgb(0, 170, 127)")
        self.wgt_debC.setObjectName("wgt_debC")
        self.lbl_hostname_debC = QtWidgets.QLabel(self.wgt_debC)
        self.lbl_hostname_debC.setGeometry(QtCore.QRect(10, 5, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_hostname_debC.setFont(font)
        self.lbl_hostname_debC.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lbl_hostname_debC.setObjectName("lbl_hostname_debC")
        self.tBtn_editHost_debC = QtWidgets.QToolButton(self.wgt_debC)
        self.tBtn_editHost_debC.setGeometry(QtCore.QRect(290, 10, 31, 31))
        self.tBtn_editHost_debC.setObjectName("tBtn_editHost_debC")
        self.lbl_mac_debC = QtWidgets.QLabel(self.wgt_debC)
        self.lbl_mac_debC.setGeometry(QtCore.QRect(10, 50, 271, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_mac_debC.setFont(font)
        self.lbl_mac_debC.setObjectName("lbl_mac_debC")
        self.lbl_ip_debC = QtWidgets.QLabel(self.wgt_debC)
        self.lbl_ip_debC.setGeometry(QtCore.QRect(10, 70, 271, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_ip_debC.setFont(font)
        self.lbl_ip_debC.setObjectName("lbl_ip_debC")
        self.lbl_mlticast_debC = QtWidgets.QLabel(self.wgt_debC)
        self.lbl_mlticast_debC.setGeometry(QtCore.QRect(10, 110, 271, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_mlticast_debC.setFont(font)
        self.lbl_mlticast_debC.setObjectName("lbl_mlticast_debC")
        self.lbl_rx_debC = QtWidgets.QLabel(self.wgt_debC)
        self.lbl_rx_debC.setGeometry(QtCore.QRect(10, 130, 271, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_rx_debC.setFont(font)
        self.lbl_rx_debC.setObjectName("lbl_rx_debC")
        self.lbl_tx_debC = QtWidgets.QLabel(self.wgt_debC)
        self.lbl_tx_debC.setGeometry(QtCore.QRect(10, 150, 271, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_tx_debC.setFont(font)
        self.lbl_tx_debC.setObjectName("lbl_tx_debC")
        self.lbl_mode_debC = QtWidgets.QLabel(self.wgt_debC)
        self.lbl_mode_debC.setGeometry(QtCore.QRect(10, 90, 271, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_mode_debC.setFont(font)
        self.lbl_mode_debC.setObjectName("lbl_mode_debC")
        self.gridLayout_6.addWidget(self.wgt_debC, 2, 0, 1, 1)
        self.wgt_sw1 = QtWidgets.QWidget(self.frm_network)
        self.wgt_sw1.setEnabled(True)
        self.wgt_sw1.setAutoFillBackground(False)
        self.wgt_sw1.setStyleSheet("background-color: rgb(170, 85, 127)")
        self.wgt_sw1.setObjectName("wgt_sw1")
        self.lbl_switchname_sw1 = QtWidgets.QLabel(self.wgt_sw1)
        self.lbl_switchname_sw1.setGeometry(QtCore.QRect(10, 5, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_switchname_sw1.setFont(font)
        self.lbl_switchname_sw1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lbl_switchname_sw1.setObjectName("lbl_switchname_sw1")
        self.lbl_rx_sw1 = QtWidgets.QLabel(self.wgt_sw1)
        self.lbl_rx_sw1.setGeometry(QtCore.QRect(10, 70, 311, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_rx_sw1.setFont(font)
        self.lbl_rx_sw1.setObjectName("lbl_rx_sw1")
        self.lbl_tx_sw1 = QtWidgets.QLabel(self.wgt_sw1)
        self.lbl_tx_sw1.setGeometry(QtCore.QRect(10, 90, 311, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_tx_sw1.setFont(font)
        self.lbl_tx_sw1.setObjectName("lbl_tx_sw1")
        self.tBtn_editSwitch_sw1 = QtWidgets.QToolButton(self.wgt_sw1)
        self.tBtn_editSwitch_sw1.setGeometry(QtCore.QRect(290, 10, 31, 31))
        self.tBtn_editSwitch_sw1.setObjectName("tBtn_editSwitch_sw1")
        self.lbl_sship_sw1 = QtWidgets.QLabel(self.wgt_sw1)
        self.lbl_sship_sw1.setGeometry(QtCore.QRect(10, 50, 311, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_sship_sw1.setFont(font)
        self.lbl_sship_sw1.setObjectName("lbl_sship_sw1")
        self.gridLayout_6.addWidget(self.wgt_sw1, 1, 2, 1, 1)
        self.gridLayout_5.addWidget(self.frm_network, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_testCmmds, "")
        self.tab_configBrowser = QtWidgets.QWidget()
        self.tab_configBrowser.setObjectName("tab_configBrowser")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_configBrowser)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab_configBrowser)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_brw_sw0 = QtWidgets.QWidget()
        self.tab_brw_sw0.setObjectName("tab_brw_sw0")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_brw_sw0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.webView_sw0 = QtWebKitWidgets.QWebView(self.tab_brw_sw0)
        self.webView_sw0.setUrl(QtCore.QUrl("http://localhost:10080/"))
        self.webView_sw0.setZoomFactor(1.0)
        self.webView_sw0.setObjectName("webView_sw0")
        self.gridLayout_3.addWidget(self.webView_sw0, 0, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_brw_sw0, "")
        self.tab_brw_sw1 = QtWidgets.QWidget()
        self.tab_brw_sw1.setObjectName("tab_brw_sw1")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_brw_sw1)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.webView_sw1 = QtWebKitWidgets.QWebView(self.tab_brw_sw1)
        self.webView_sw1.setUrl(QtCore.QUrl("http://localhost:10080/"))
        self.webView_sw1.setZoomFactor(1.0)
        self.webView_sw1.setObjectName("webView_sw1")
        self.gridLayout_4.addWidget(self.webView_sw1, 0, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_brw_sw1, "")
        self.gridLayout_2.addWidget(self.tabWidget_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_configBrowser, "")
        self.gridLayout.addWidget(self.tabWidget, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lbl_hostname_debB.setText(_translate("Dialog", "debB"))
        self.tBtn_editHost_debB.setText(_translate("Dialog", "..."))
        self.lbl_mac_debB.setText(_translate("Dialog", "MAC  Address:"))
        self.lbl_ip_debB.setText(_translate("Dialog", "IPv4 Address:"))
        self.lbl_mlticast_debB.setText(_translate("Dialog", "Multicast Group:"))
        self.lbl_rx_debB.setText(_translate("Dialog", "Rx:"))
        self.lbl_tx_debB.setText(_translate("Dialog", "Tx:"))
        self.lbl_mode_debB.setText(_translate("Dialog", "Mode:"))
        self.btn_testSettings.setText(_translate("Dialog", "Test Settings"))
        self.btn_runTest.setText(_translate("Dialog", "Run Test"))
        self.btn_exit.setText(_translate("Dialog", "Exit"))
        self.lbl_hostname_debH.setText(_translate("Dialog", "debH"))
        self.tBtn_editHost_debH.setText(_translate("Dialog", "..."))
        self.lbl_mac_debH.setText(_translate("Dialog", "MAC  Address:"))
        self.lbl_ip_debH.setText(_translate("Dialog", "IPv4 Address:"))
        self.lbl_mlticast_debH.setText(_translate("Dialog", "Multicast Group:"))
        self.lbl_rx_debH.setText(_translate("Dialog", "Rx:"))
        self.lbl_tx_debH.setText(_translate("Dialog", "Tx:"))
        self.lbl_mode_debH.setText(_translate("Dialog", "Mode:"))
        self.lbl_hostname_debG.setText(_translate("Dialog", "debG"))
        self.tBtn_editHost_debG.setText(_translate("Dialog", "..."))
        self.lbl_mac_debG.setText(_translate("Dialog", "MAC  Address:"))
        self.lbl_ip_debG.setText(_translate("Dialog", "IPv4 Address:"))
        self.lbl_mlticast_debG.setText(_translate("Dialog", "Multicast Group:"))
        self.lbl_rx_debG.setText(_translate("Dialog", "Rx:"))
        self.lbl_tx_debG.setText(_translate("Dialog", "Tx:"))
        self.lbl_mode_debG.setText(_translate("Dialog", "Mode:"))
        self.lbl_hostname_debD.setText(_translate("Dialog", "debD"))
        self.tBtn_editHost_debD.setText(_translate("Dialog", "..."))
        self.lbl_mac_debD.setText(_translate("Dialog", "MAC  Address:"))
        self.lbl_ip_debD.setText(_translate("Dialog", "IPv4 Address:"))
        self.lbl_mlticast_debD.setText(_translate("Dialog", "Multicast Group:"))
        self.lbl_rx_debD.setText(_translate("Dialog", "Rx:"))
        self.lbl_tx_debD.setText(_translate("Dialog", "Tx:"))
        self.lbl_mode_debD.setText(_translate("Dialog", "Mode:"))
        self.lbl_hostname_debE.setText(_translate("Dialog", "debE"))
        self.tBtn_editHost_debE.setText(_translate("Dialog", "..."))
        self.lbl_mac_debE.setText(_translate("Dialog", "MAC  Address:"))
        self.lbl_ip_debE.setText(_translate("Dialog", "IPv4 Address:"))
        self.lbl_mlticast_debE.setText(_translate("Dialog", "Multicast Group:"))
        self.lbl_rx_debE.setText(_translate("Dialog", "Rx:"))
        self.lbl_tx_debE.setText(_translate("Dialog", "Tx:"))
        self.lbl_mode_debE.setText(_translate("Dialog", "Mode:"))
        self.lbl_hostname_debF.setText(_translate("Dialog", "debF"))
        self.tBtn_editHost_debF.setText(_translate("Dialog", "..."))
        self.lbl_mac_debF.setText(_translate("Dialog", "MAC  Address:"))
        self.lbl_ip_debF.setText(_translate("Dialog", "IPv4 Address:"))
        self.lbl_mlticast_debF.setText(_translate("Dialog", "Multicast Group:"))
        self.lbl_rx_debF.setText(_translate("Dialog", "Rx:"))
        self.lbl_tx_debF.setText(_translate("Dialog", "Tx:"))
        self.lbl_mode_debF.setText(_translate("Dialog", "Mode:"))
        self.lbl_hostname_debA.setText(_translate("Dialog", "debA"))
        self.tBtn_editHost_debA.setText(_translate("Dialog", "..."))
        self.lbl_mac_debA.setText(_translate("Dialog", "MAC  Address:"))
        self.lbl_ip_debA.setText(_translate("Dialog", "IPv4 Address:"))
        self.lbl_mlticast_debA.setText(_translate("Dialog", "Multicast Group:"))
        self.lbl_rx_debA.setText(_translate("Dialog", "Rx:"))
        self.lbl_tx_debA.setText(_translate("Dialog", "Tx:"))
        self.lbl_mode_debA.setText(_translate("Dialog", "Mode:"))
        self.lbl_switchname_sw0.setText(_translate("Dialog", "switch0"))
        self.lbl_rx_sw0.setText(_translate("Dialog", "Rx:"))
        self.lbl_tx_sw0.setText(_translate("Dialog", "Tx:"))
        self.tBtn_editSwitch_sw0.setText(_translate("Dialog", "..."))
        self.lbl_sship_sw0.setText(_translate("Dialog", "SSH IPv4:"))
        self.lbl_hostname_debC.setText(_translate("Dialog", "debC"))
        self.tBtn_editHost_debC.setText(_translate("Dialog", "..."))
        self.lbl_mac_debC.setText(_translate("Dialog", "MAC  Address:"))
        self.lbl_ip_debC.setText(_translate("Dialog", "IPv4 Address:"))
        self.lbl_mlticast_debC.setText(_translate("Dialog", "Multicast Group:"))
        self.lbl_rx_debC.setText(_translate("Dialog", "Rx:"))
        self.lbl_tx_debC.setText(_translate("Dialog", "Tx:"))
        self.lbl_mode_debC.setText(_translate("Dialog", "Mode:"))
        self.lbl_switchname_sw1.setText(_translate("Dialog", "switch1"))
        self.lbl_rx_sw1.setText(_translate("Dialog", "Rx:"))
        self.lbl_tx_sw1.setText(_translate("Dialog", "Tx:"))
        self.tBtn_editSwitch_sw1.setText(_translate("Dialog", "..."))
        self.lbl_sship_sw1.setText(_translate("Dialog", "SSH IPv4:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_testCmmds), _translate("Dialog", "Test Commands"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_brw_sw0), _translate("Dialog", "switch0"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_brw_sw1), _translate("Dialog", "switch1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_configBrowser), _translate("Dialog", "Switch Config Browser"))

from PyQt5 import QtWebKitWidgets
