#!/bin/sh

hosts=8
count=1
while [ $count -le $hosts ]
do
	#Bring down bridges and delete
	ifconfig swbr${count} down
	brctl delbr swbr${count}

	#Delete TAP devices
	tunctl -d sw_tap${count}
	tunctl -d deb${count}_tap

	((count++))	
done

#Interswitch TAPS
ifconfig swswbr down
brctl delbr swswbr
tunctl -d sw_sw_tap0
tunctl -d sw_sw_tap1