#!/bin/bash

#Streaming Test for Multicast 
#Setup: 4 Streams
#
#	A->E,F,G,H
#	B->E,F,G,H
#	C->E,F,G,H
#	D->E,F,G,H
#

echo "Test running.."

#Start servers (Multicast receving end) on hosts E-H
#Host: debE
sshpass -v -p 'debian' ssh debian@10.10.11.35 -p 10005 'iperf -s -u -B 224.0.67.67 -i 1 > debE_mcst4_67' &
sleep 1
sshpass -v -p 'debian' ssh debian@10.10.11.35 -p 10005 'iperf -s -u -B 224.0.67.68 -i 1 > debE_mcst4_68' &
sleep 1
sshpass -v -p 'debian' ssh debian@10.10.11.35 -p 10005 'iperf -s -u -B 224.0.67.69 -i 1 > debE_mcst4_69' & 
sleep 1
sshpass -v -p 'debian' ssh debian@10.10.11.35 -p 10005 'iperf -s -u -B 224.0.67.70 -i 1 > debE_mcst4_70' &
sleep 1
echo "debE servers up."

#Host: debF
sshpass -v -p 'debian' ssh debian@10.10.11.35 -p 10006 'iperf -s -u -B 224.0.67.67 -i 1 > debF_mcst4_67' &
sleep 1
sshpass -v -p 'debian' ssh debian@10.10.11.35 -p 10006 'iperf -s -u -B 224.0.67.68 -i 1 > debF_mcst4_68' &
sleep 1
sshpass -v -p 'debian' ssh debian@10.10.11.35 -p 10006 'iperf -s -u -B 224.0.67.69 -i 1 > debF_mcst4_69' &
sleep 1
sshpass -v -p 'debian' ssh debian@10.10.11.35 -p 10006 'iperf -s -u -B 224.0.67.70 -i 1 > debF_mcst4_70' &
sleep 1
echo "debF servers up."

#Host: debG
sshpass -v -p 'debian' ssh debian@10.10.11.35 -p 10007 'iperf -s -u -B 224.0.67.67 -i 1 > debG_mcst4_67' &
sleep 1
sshpass -v -p 'debian' ssh debian@10.10.11.35 -p 10007 'iperf -s -u -B 224.0.67.68 -i 1 > debG_mcst4_68' &
sleep 1
sshpass -v -p 'debian' ssh debian@10.10.11.35 -p 10007 'iperf -s -u -B 224.0.67.69 -i 1 > debG_mcst4_69' &
sleep 1
sshpass -v -p 'debian' ssh debian@10.10.11.35 -p 10007 'iperf -s -u -B 224.0.67.70 -i 1 > debG_mcst4_70' &
sleep 1
echo "debG servers up."

#Host: debH
sshpass -v -p 'debian' ssh debian@10.10.11.35 -p 10008 'iperf -s -u -B 224.0.67.67 -i 1 > debH_mcst4_67' &
sleep 1
sshpass -v -p 'debian' ssh debian@10.10.11.35 -p 10008 'iperf -s -u -B 224.0.67.68 -i 1 > debH_mcst4_68' &
sleep 1
sshpass -v -p 'debian' ssh debian@10.10.11.35 -p 10008 'iperf -s -u -B 224.0.67.69 -i 1 > debH_mcst4_69' &
sleep 1
sshpass -v -p 'debian' ssh debian@10.10.11.35 -p 10008 'iperf -s -u -B 224.0.67.70 -i 1 > debH_mcst4_70' &
sleep 1
echo "debH servers up."

#Start Clients (Multicast transmitting end) on hosts A-D
#Host: debA
sshpass -v -p 'debian' ssh debian@10.10.11.35 -p 10001 'iperf -c 224.0.67.67 -u --ttl 5 -t 5 -l 64 -b 30k' &
#Host: debB
sshpass -v -p 'debian' ssh debian@10.10.11.35 -p 10002 'iperf -c 224.0.67.68 -u --ttl 5 -t 5 -l 64 -b 30k' &
#Host: debC
sshpass -v -p 'debian' ssh debian@10.10.11.35 -p 10003 'iperf -c 224.0.67.69 -u --ttl 5 -t 5 -l 64 -b 30k' &
#Host: debD
sshpass -v -p 'debian' ssh debian@10.10.11.35 -p 10004 'iperf -c 224.0.67.70 -u --ttl 5 -t 5 -l 64 -b 30k' &&

#Kill all iperf servers. For some reason I need to run pkill iperf twice
sshpass -v -p 'debian' ssh debian@10.10.11.35 -p 10005 'for pid in $(pidof iperf); do kill -9 $pid && sleep 0.5; done && pidof iperf' ;
sshpass -v -p 'debian' ssh debian@10.10.11.35 -p 10006 'for pid in $(pidof iperf); do kill -9 $pid && sleep 0.5; done && pidof iperf' ;
sshpass -v -p 'debian' ssh debian@10.10.11.35 -p 10007 'for pid in $(pidof iperf); do kill -9 $pid && sleep 0.5; done && pidof iperf' ;
sshpass -v -p 'debian' ssh debian@10.10.11.35 -p 10008 'for pid in $(pidof iperf); do kill -9 $pid && sleep 0.5; done && pidof iperf' ;

sleep 5

echo "Test Complete."


